# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 667aa4040657f5825890dc424e87f60742b8bf576f22a1783ba23999f1c84c2dfb036271739642849cf62ad9d9d76e99df319d4a99cbd482319155d2f0cff61e

test:
  secret_key_base: de8ed6c74a1a7d1b4f387a2f64fb274313d000f91b8ceaa0ec19c91b550d1569d3946fc4d385062b4e5f9a680d033f423c54162ed38350c2a649a1d9c23842e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
